envs:
  default:
    remotePinning:
      defaultServiceConfig:
        limits:
          maxQueuedItems: 0
          maxPinningItems: 0
          maxPinnedItems: 0

          storageLimit: False
          storageMaxMb: 0

        notify:
          alertOnFailed: False
          alertOnPinning: True
          alertOnPinned: True
          alertOnQueued: False

      # Remote Pinning Service list (scanned from the daemon)
      services: []

    objects:
      #
      # Local pinning orchestrator object configuration
      #
      lpOrchestrator:
        # Max empty-no-progress messages to tolerate before
        # giving up on an object we're trying to pin
        maxStalledMessages: 24

        # Delay (in seconds) after which a pinned item will
        # be considered inactive (and disappear from the
        # pinning status widget)
        pinnedExpires: 120

        # Pinning queue configuration
        queue:
          type: 'standard'
          size: 1024
