envs:
  default:
    peers:
      didLoadTimeout: 10
      didLoadAttempts: 5

      liveness:
        didPingEvery: 300
        didPingCallTimeout: 30

        inactiveNoIdent: 300

      didFail:
        sleepInterval: 60

      watcherTask:
        sleepInterval: 180
