envs:
  default:
    language: en

    languagesAvailable:
      - code: en
        displayName: 'English'

    asyncio:
      # aiojobs schedulers
      aioSchedulers:
        main:
          closeTimeout: 0.5
          jobsLimit: 300
          pendingJobsLimit: 2000

          shutdown:
            closeAttempts: 10
            closeTimeout: 5.0

      # Tasks settings
      tasks:
        cancelTimeout: 0.2

    locations:
      downloadsPath: null
